### PR TITLE
Fix accessibility issues

### LINKED ISSUE #145: Links as Buttons Activation via Spacebar
Buttons are supposed to be able to be activated by spacebar for a11y. I think we should add some JavaScript to site-wide Orchid that selects all `<a class="btn" ...>` elements and makes a spacebar press while focused behave like a click and pressing enter.

In addition, we could add some code that adds `role="button"` if it isn't already present for these elements.

### PR DESCRIPTION
**Pull request by wkdewey**
Fixes #145

### CODE REVIEW

**Comment by wkdewey** [comment]
Also fixes #125

**Comment by wkdewey** [comment]
Also fixes #222 . All the js files should be in the right place now and all the manifests should be good.

File: vendor/assets/javascripts/modernizr-custom.js [hunk 1]
```diff
@@ -0,0 +1,255 @@
+/*!
```
Comment (techgique) [inline vendor/assets/javascripts/modernizr-custom.js:1]: This is an old version of Modernizr. We should use the latest release: https://github.com/Modernizr/Modernizr/releases

And for actual use by apps, we do want the minified version. Using an unminified version should only be done if debugging something and not committed for use in production.

And could you document the steps used to "build" it so others can update easily in the future? Probably in `/docs/installation.md`

File: app/assets/stylesheets/orchid.scss [hunk 2]
```diff
@@ -121,3 +121,6 @@
     content: " …";
   }
 }
+
+//uncollapse if no javascript
+.no-js .collapse { display: block; }
```
Comment (techgique) [inline app/assets/stylesheets/orchid.scss:126]: Why was this moved to the bottom of the file? I would prefer it where it was before for CSS organization and don't see anything else in our styles that would conflict in terms of CSS precedence here. At least at a glance.

File: app/assets/config/orchid/manifest.js [hunk 3]
```diff
@@ -1,5 +1,6 @@
 // Declare Orchid's assets for auto and pre-compilation
 // which can't be declared with portable relative paths from the generated app
 //= link_tree ../../images/orchid
+//= link_tree ../../images/favicon
```
Comment (techgique) [inline app/assets/config/orchid/manifest.js:4]: In the future I wouldn't re-commit things that are fixed in another branch to other branches like this. It conflates what branch/PR is handling what and could be error-prone if there are differences between the commits across branches.

If the commits are fixing errors like this, I recommend fixing them but just leaving the fix uncommitted on the branch where other work is being done because they should only be committed for merging on the one other branch.

It wasn't applicable in this case, but if we had gotten the other branch / PR merged before this was re-committed, I would recommend rebasing this branch off of `dev` so the branches merged into `dev` since this branch was started off of it are included as if you had created the branch off the updated `dev` branch.

File: app/controllers/items_controller.rb [hunk 4]
```diff
@@ -84,7 +84,7 @@ def show
 
   # display a flash message if the API response has an error
   def check_response
-    if !@res || (@res.key?("error") && @res.error)
+    if !@res || @res.error
```
Comment (techgique) [inline app/controllers/items_controller.rb:87]: Same comment here as with what was done with the favicon commit regarding fixes made in other branches. This will actually conflict with what I improved upon the fix in the other branch now because it isn't the same. So you'll have to resolve the conflict and be careful to commit what was done in the other branch rather than this version.

*checks the PR page*

Oh no. Even worse, it's not even flagging it as a conflict. So if I hadn't looked at this closely, this branch would have been merged into `dev` and undone the fixes from the `error_checking` PR :weary:

Honestly, this is probably a good opportunity for you to learn interactive rebasing. That would be the way to make this branch/PR the cleaneast, but we can handle that in January. It would be a good lesson for everyone on the dev team :bulb:

**Review by techgique — CHANGES_REQUESTED** [review]
Some additional work for the new year :partying_face:

File: app/controllers/items_controller.rb (hunk 4 above)
Comment (techgique) [reply app/controllers/items_controller.rb:87]: Scratch that. It wasn't showing the conflict yet because I hadn't merged the other PR back into `dev`. Now that I did that, it does show the conflict. Still, an interactive rebase would be the best way to remove the work done on the other branches from this one :+1:

Comment (wkdewey) [reply app/controllers/items_controller.rb:87]: I realized this may be an issue, but it's hard to test code when it causes errors. Don't know if it was the case, but what if there were changes in the same file? It would be hard to leave that uncomitted.

Comment (wkdewey) [reply app/controllers/items_controller.rb:87]: maybe I could rebase while I'm still working on the branch?

Comment (techgique) [reply app/controllers/items_controller.rb:87]: An entire file's changes don't have to be committed. I use a git GUI program for line-by-line staging where I want some changes in a file committed and others not. I've never looked into how to do it from the command line, but it must be possible that way too. Just way easier with a GUI.

Now that the other branches have been merged, yeah it is a good time for rebasing. We'll go over it when everyone is back :+1:

File: app/assets/javascripts/global/button.js [hunk 5]
```diff
@@ -0,0 +1,11 @@
+window.addEventListener("load", () => {
+    const buttons = document.querySelectorAll("a[role='button']");
+    buttons.forEach((element) => {
+        element.addEventListener("keyup", (event) => {
+            if (event.keyCode === 32) {
+                event.preventDefault();
+                element.click();
+            }
+        })
```
[the remark this answers is not in the document]
Comment (wkdewey) [reply app/assets/javascripts/global/button.js:9]: fixed

File: app/views/items/browse.html.erb [hunk 6]
```diff
@@ -1,6 +1,6 @@
 <%= render_overridable "items", "browse_header" %>
 
-<h3><%= t "browse.browse_type", default: "Browse by" %>:</h3>
+<h2><%= t "browse.browse_type", default: "Browse by" %>:</h2>
```
[the remark this answers is not in the document]
Comment (wkdewey) [reply app/views/items/browse.html.erb:3]: fixed

File: vendor/assets/javascripts/modernizr-custom.js (hunk 1 above)
Comment (wkdewey) [reply vendor/assets/javascripts/modernizr-custom.js]: I have updated it to the latest version and updated the docs.

File: app/assets/stylesheets/orchid.scss (hunk 2 above)
Comment (wkdewey) [reply app/assets/stylesheets/orchid.scss]: fixed

File: app/controllers/items_controller.rb (hunk 4 above)
Comment (wkdewey) [reply app/controllers/items_controller.rb]: I attempted a rebase, removing the commits dealing with the favicon assets and the error checking. Hope I didn't mess anything up! It looks like there is no more merge conflict.

Comment (techgique) [reply app/controllers/items_controller.rb]: I think the favicon commit is still there but looks like the error checking commit was removed in the rebase. Would still like to go through the process with Karin and Sarita to help them understand how it can be used.

**Comment by techgique** [comment]
Another thing we probably want to tackle with this PR is there are some `<a>` elements that have the `btn` classes but don't have the `role="button"` attribute. We should probably review/standardize that alongside the JS code that leverages that for the keyboard accessibility.
